title: AutoCon 4 - Design-Driven Automation - Lab Guide
description: Lab guide for the AutoCon 4 Design-Driven Automation workshop
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme